Add survey for CBBS imaging platform
psychoinformatics-de/dmc pull request #33
Opened 2017-11-03 12:44 UTC by bpoldrack

Initial draft to add a survey for CBBS imaging platform.

Please review and leave your comments, @mih and @aqw !

2017-11-03 12:45 UTC, mih commented
Is it online?

2017-11-06 12:52 UTC, aqw requested changes

2017-11-06 12:52 UTC, aqw commented on www/cbbs_imaging/index.html
> +  <meta name="description" content="How-Do-You-Science Demo" />
This should be adjusted.

2017-11-06 12:52 UTC, aqw commented on www/cbbs_imaging/index.html
> +          <option>German Centre for Neurodegenerative Diseases</option>
Add "Other"?

2017-11-06 12:52 UTC, aqw commented on www/cbbs_imaging/index.html
> +          <option>OvGU (without Hospital)</option>
s/without Hospital/University only/

2017-11-06 12:52 UTC, aqw commented on www/cbbs_imaging/index.html
> +      <h2>How many people are doing data analyses in your lab?</h2>
Are we emphasizing data here? It just feels odd. Hard to analyze without data.

2017-11-06 12:52 UTC, aqw commented on www/cbbs_imaging/index.html
> +      <p>Does your lab <em>use</em> shared computing infrastructure?</p>
"such as" might help

2017-11-06 12:52 UTC, aqw commented on www/cbbs_imaging/index.html
> +      <p>What methods/tools developed in your lab would you like to become available?</p>
For others, for self? What's primary motivation? I think people will parse this statement.

2017-11-06 12:52 UTC, aqw commented on www/cbbs_imaging/index.html
> +          value='dat'> dat</label>
datalad?

2017-11-06 12:52 UTC, aqw commented on www/cbbs_imaging/index.html
> +      <p>What Scanners are used by your lab?</p>
Scanners should be lower case

2017-11-06 12:52 UTC, aqw commented on www/cbbs_imaging/index.html
> +      <h2>Amount of acquisitions</h2>
Amount is wrong word. TODO: reword (uncertain of my suggestion)

2017-11-06 12:52 UTC, aqw commented on www/cbbs_imaging/index.html
> +      <p>What's the timeframe from end of acquisition until submission of a publication?</p>
The "typical" timeframe

2017-11-06 12:52 UTC, aqw commented on www/cbbs_imaging/success.html
> +  <title>Victory! — How Do You Science?</title>
Update

2017-11-06 12:52 UTC, aqw commented on www/cbbs_imaging/success.html
> +  <meta name="description" content="How-do-you-science survey" />
Update

2017-11-06 13:47 UTC, bpoldrack commented
Thanks, @aqw.

Online now: http://howdoyouscience.net/cbbs_imaging/

2017-11-08 09:59 UTC, mih commented
Merging, final touches in master

2017-11-08 09:59 UTC, merged